from typing import List, Dict, Any

section_list = [
    "",
    "1. Short title.—This Act may be called the Indian Contract Act, 1872.",
    "2. Interpretation-clause.—In this Act the following words and expressions are used in the following senses, unless a contrary intention appears from the context:—\n(a) When one person signifies to another his willingness to do or to abstain from doing anything, with a view to obtaining the assent of that other to such act or abstinence, he is said to make a proposal;\n(b) When the person to whom the proposal is made signifies his assent thereto, the proposal is said to be accepted. A proposal, when accepted, becomes a promise;\n(c) The person making the proposal is called the “promisor”, and the person accepting the proposal is called the “promisee”;\n(d) When, at the desire of the promisor, the promisee or any other person has done or abstained from doing, or does or abstains from doing, or promises to do or to abstain from doing, something, such act or abstinence or promise is called a consideration for the promise;\n(e) Every promise and every set of promises, forming the consideration for each other, is an agreement;\n(f) Promises which form the consideration or part of the consideration for each other are called reciprocal promises;\n(g) An agreement not enforceable by law is said to be void;\n(h) An agreement enforceable by law is a contract;\n(i) An agreement which is enforceable by law at the option of one or more of the parties thereto, but not at the option of the other or others, is a voidable contract;\n(j) A contract which ceases to be enforceable by law becomes void when it ceases to be enforceable.",
    "3. Communication, acceptance and revocation of proposals.—The communication of proposals, the acceptance of proposals, and the revocation of proposals and acceptances, respectively, are deemed to be made by any act or omission of the party proposing, accepting or revoking by which he intends to communicate such proposal, acceptance or revocation, or which has the effect of communicating it.",
    "4. Communication when complete.—The communication of a proposal is complete when it comes to the knowledge of the person to whom it is made. The communication of an acceptance is complete,— as against the proposer, when it is put in a course of transmission to him, so as to be out of the power of the acceptor; as against the acceptor, when it comes to the knowledge of the proposer. The communication of a revocation is complete,— as against the person who makes it, when it is put into a course of transmission to the person to whom it is made, so as to be out of the power of the person who makes it; as against the person to whom it is made, when it comes to his knowledge.",
    "5. Revocation of proposals and acceptances.—A proposal may be revoked at any time before the communication of its acceptance is complete as against the proposer, but not afterwards. An acceptance may be revoked at any time before the communication of the acceptance is complete as against the acceptor, but not afterwards.",
    "6. Revocation how made.—A proposal is revoked—\n(1) by the communication of notice of revocation by the proposer to the other party;\n(2) by the lapse of the time prescribed in such proposal for its acceptance, or, if no time is so prescribed, by the lapse of a reasonable time, without communication of the acceptance;\n(3) by the failure of the acceptor to fulfil a condition precedent to acceptance; or\n(4) by the death or insanity of the proposer, if the fact of his death or insanity comes to the knowledge of the acceptor before acceptance.",
    "7. Acceptance must be absolute.—In order to convert a proposal into a promise, the acceptance must—\n(1) be absolute and unqualified;\n(2) be expressed in some usual and reasonable manner, unless the proposal prescribes the manner in which it is to be accepted. If the proposal prescribes a manner in which it is to be accepted, and the acceptance is not made in such manner, the proposer may, within a reasonable time after the acceptance is communicated to him, insist that his proposal shall be accepted in the prescribed manner, and not otherwise; but if he fails to do so, he accepts the acceptance.",
    "8. Acceptance by performing conditions, or receiving consideration.—Performance of the conditions of a proposal, or the acceptance of any consideration for a reciprocal promise which may be offered with a proposal, is an acceptance of the proposal.",
    "9. Promises, express and implied.—In so far as the proposal or acceptance of any promise is made in words, the promise is said to be express. In so far as such proposal or acceptance is made otherwise than in words, the promise is said to be implied.",
    "10. What agreements are contracts.—All agreements are contracts if they are made by the free consent of parties competent to contract, for a lawful consideration and with a lawful object, and are not hereby expressly declared to be void.",
    "11. Who are competent to contract.—Every person is competent to contract who is of the age of majority according to the law to which he is subject, and who is of sound mind, and is not disqualified from contracting by any law to which he is subject.",
    "12. What is a sound mind for the purposes of contracting.—A person is said to be of sound mind for the purpose of making a contract, if, at the time when he makes it, he is capable of understanding it and of forming a rational judgment as to its effect upon his interests.",
    "13. “Consent” defined.—Two or more persons are said to consent when they agree upon the same thing in the same sense.",
    "14. “Free consent” defined.—Consent is said to be free when it is not caused by—\n(1) coercion, as defined in section 15, or\n(2) undue influence, as defined in section 16, or\n(3) fraud, as defined in section 17, or\n(4) misrepresentation, as defined in section 18, or\n(5) mistake, subject to the provisions of sections 20, 21 and 22.",
    "15. “Coercion” defined.—“Coercion” is the committing, or threatening to commit, any act forbidden by the Indian Penal Code (45 of 1860) or the unlawful detaining, or threatening to detain, any property, to the prejudice of any person whatever, with the intention of causing any person to enter into an agreement.",
    "16. “Undue influence” defined.—(1) A contract is said to be induced by “undue influence” where the relations subsisting between the parties are such that one of the parties is in a position to dominate the will of the other and uses that position to obtain an unfair advantage over the other.",
    "17. “Fraud” defined.—“Fraud” means and includes any of the following acts committed by a party to a contract, or with his connivance, or by his agent, with intent to deceive another party thereto or his agent, or to induce him to enter into the contract:—\n(1) the suggestion, as a fact, of that which is not true, by one who does not believe it to be true;\n(2) the active concealment of a fact by one having knowledge or belief of the fact;\n(3) a promise made without any intention of performing it;\n(4) any other act fitted to deceive;\n(5) any such act or omission as the law specially declares to be fraudulent.",
    "18. “Misrepresentation” defined.—“Misrepresentation” means and includes—\n(1) the positive assertion, in a manner not warranted by the information of the person making it, of that which is not true, though he believes it to be true;\n(2) any breach of duty which, without an intent to deceive, gains an advantage to the person committing it, or any one claiming under him, by misleading another to his prejudice, or to the prejudice of any one claiming under him;\n(3) causing, however innocently, a party to an agreement, to make a mistake as to the substance of the thing which is the subject of the agreement.",
    "19. Voidability of agreements without free consent.—When consent to an agreement is caused by coercion, fraud or misrepresentation, the agreement is a contract voidable at the option of the party whose consent was so caused.",
    "19A. Power to set aside contract induced by undue influence.—When consent to an agreement is caused by undue influence, the agreement is a contract voidable at the option of the party whose consent was so caused.",
    "20. Agreement void where both parties are under mistake as to matter of fact.—Where both the parties to an agreement are under a mistake as to a matter of fact essential to the agreement, the agreement is void.",
    "21. Effect of mistakes as to law.—A contract is not voidable because it was caused by a mistake as to any law in force in India; but a mistake as to a law not in force in India has the same effect as a mistake of fact.",
    "22. Contract caused by mistake of one party as to matter of fact.—A contract is not voidable merely because it was caused by one of the parties to it being under a mistake as to a matter of fact.",
    "23. What considerations and objects are lawful, and what not.—The consideration or object of an agreement is lawful, unless— it is forbidden by law; or is of such a nature that, if permitted, it would defeat the provisions of any law; or is fraudulent; or involves or implies, injury to the person or property of another; or the Court regards it as immoral, or opposed to public policy.",
    "24. Agreements void, if considerations and objects unlawful in part.—If any part of a single consideration for one or more objects, or any one or any part of any one of several considerations for a single object, is unlawful, the agreement is void.",
    "25. Agreement without consideration, void, unless it is in writing and registered or is a promise to compensate for something done or is a promise to pay a debt barred by limitation law.—An agreement made without consideration is void, unless—\n(1) it is expressed in writing and registered under the law for the time being in force for the registration of documents, and is made on account of natural love and affection between parties standing in a near relation to each other; or unless\n(2) it is a promise to compensate, wholly or in part, a person who has already voluntarily done something for the promisor, or something which the promisor was legally compellable to do; or unless\n(3) it is a promise, made in writing and signed by the person to be charged therewith, or by his agent generally or specially authorized in that behalf, to pay wholly or in part a debt of which the creditor might have enforced payment but for the law for the limitation of suits.",
    "26. Agreement in restraint of marriage, void.—Every agreement in restraint of the marriage of any person, other than a minor, is void.",
    "27. Agreement in restraint of trade, void.—Every agreement by which any one is restrained from exercising a lawful profession, trade or business of any kind, is to that extent void.",
    "28. Agreements in restraint of legal proceedings, void.—Every agreement, by which any party thereto is restricted absolutely from enforcing his rights under or in respect of any contract, by the usual legal proceedings in the ordinary tribunals, or which limits the time within which he may thus enforce his rights, is void to that extent.",
    "29. Agreements void for uncertainty.—Agreements, the meaning of which is not certain, or capable of being made certain, are void.",
    "30. Agreements by way of wager, void.—Agreements by way of wager are void; and no suit shall be brought for recovering anything alleged to be won on any wager, or entrusted to any person to abide the result of any game or other uncertain event on which any wager is made.",
    "31. “Contingent contract” defined.—A “contingent contract” is a contract to do or not to do something, if some event, collateral to such contract, does or does not happen.",
    "32. Enforcement of contracts contingent on an event happening.—Contingent contracts to do or not to do anything if an uncertain future event happens cannot be enforced by law unless and until that event has happened. If the event becomes impossible, such contracts become void.",
    "33. Enforcement of contracts contingent on an event not happening.—Contingent contracts to do or not to do anything if an uncertain future event does not happen can be enforced when the happening of that event becomes impossible, and not before.",
    "34. When event on which contract is contingent to be deemed impossible, if it is the future conduct of a living person.—If the future event on which a contract is contingent is the way in which a person will act at an unspecified time, the event shall be considered to become impossible when such person does anything which renders it impossible that he should so act within any definite time, or otherwise than under further contingencies.",
    "35. When contracts become void which are contingent on happening of specified event within fixed time.—Contingent contracts to do or not to do anything if a specified uncertain event happens within a fixed time become void if, at the expiration of the time fixed, such event has not happened, or if, before the time fixed, such event becomes impossible.",
    "36. Agreement contingent on impossible events void.—Contingent agreements to do or not to do anything, if an impossible event happens, are void, whether the impossibility of the event is known or not to the parties to the agreement at the time when it is made.",
    "37. Obligation of parties to contracts.—The parties to a contract must either perform, or offer to perform, their respective promises, unless such performance is dispensed with or excused under the provisions of this Act, or of any other law.",
    "38. Effect of refusal to accept offer of performance.—Where a promisor has made an offer of performance to the promisee, and the offer has not been accepted, the promisor is not responsible for non-performance, nor does he thereby lose his rights under the contract.",
    "39. Effect of refusal of party to perform promise wholly.—When a party to a contract has refused to perform, or disabled himself from performing, his promise in its entirety, the promisee may put an end to the contract, unless he has signified, by words or conduct, his acquiescence in its continuance.",
    "40. Person by whom promise is to be performed.—If it appears from the nature of the case that it was the intention of the parties to any contract that any promise contained in it should be performed by the promisor himself, such promise must be performed by the promisor. In other cases, the promisor or his representatives may employ a competent person to perform it.",
    "41. Effect of accepting performance from third person.—When a promisee accepts performance of the promise from a third person, he cannot afterwards enforce it against the promisor.",
    "42. Devolution of joint liabilities.—When two or more persons have made a joint promise, then, unless a contrary intention appears by the contract, all such persons, during their joint lives, and, after the death of any of them, his representative jointly with the survivor or survivors, and, after the death of the last survivor, the representatives of all jointly, must fulfil the promise.",
    "43. Any one of joint promisors may be compelled to perform.—When two or more persons make a joint promise, the promisee may, in the absence of express agreement to the contrary, compel any one or more of such joint promisors to perform the whole of the promise.",
    "44. Effect of release of one joint promisor.—Where two or more persons have made a joint promise, a release of one of such joint promisors by the promisee does not discharge the other joint promisor or joint promisors; neither does it free the joint promisor so released from responsibility to the other joint promisor or joint promisors.",
    "45. Devolution of joint rights.—When a person has made a promise to two or more persons jointly, then, unless a contrary intention appears from the contract, the right to claim performance rests, as between him and them, with them during their joint lives, and, after the death of any of them, with the representative of such deceased person jointly with the survivor or survivors, and, after the death of the last survivor, with the representatives of all jointly.",
    "46. Time for performance of promise, when no application is to be made and no time is specified.—Where, by the contract, a promisor is to perform his promise without application by the promisee, and no time for performance is specified, the engagement must be performed within a reasonable time.",
    "47. Time and place for performance of promise, where time is specified and no application to be made.—When a promise is to be performed on a certain day, and the promisor has undertaken to perform it without application by the promisee, the promisor may perform it at any time during the usual hours of business on such day and at the place at which the promise ought to be performed.",
    "48. Application for performance on certain day to be at proper time and place.—When a promise is to be performed on a certain day, and the promisor has not undertaken to perform it without application by the promisee, it is the duty of the promisee to apply for performance at a proper place and within the usual hours of business.",
    "49. Place for performance of promise, where no application to be made and no place fixed for performance.—When a promise is to be performed without application by the promisee, and no place is fixed for the performance of it, it is the duty of the promisor to apply to the promisee to appoint a reasonable place for the performance of the promise, and to perform it at such place.",
    "50. Performance in manner or at time prescribed or sanctioned by promisee.—The performance of any promise may be made in any manner, or at any time which the promisee prescribes or sanctions.",
    "51. Promisor not bound to perform, unless reciprocal promisee ready and willing to perform.—When a contract consists of reciprocal promises to be simultaneously performed, no promisor need perform his promise unless the promisee is ready and willing to perform his reciprocal promise.",
    "52. Order of performance of reciprocal promises.—Where the order in which reciprocal promises are to be performed is expressly fixed by the contract, they shall be performed in that order; and where the order is not expressly fixed by the contract, they shall be performed in that order which the nature of the transaction requires.",
    "53. Liability of party preventing event on which the contract is to take effect.—When a contract contains reciprocal promises, and one party to the contract prevents the other from performing his promise, the contract becomes voidable at the option of the party so prevented; and he is entitled to compensation from the other party for any loss which he may sustain in consequence of the non-performance of the contract.",
    "54. Effect of default as to that promise which should be first performed, in contract consisting of reciprocal promises.—When a contract consists of reciprocal promises, such that one of them cannot be performed, or that its performance cannot be claimed till the other has been performed, and the promisor of the promise last mentioned fails to perform it, such promisor cannot claim the performance of the reciprocal promise, and must make compensation to the other party to the contract for any loss which such other party may sustain by the non-performance of the contract.",
    "55. Effect of failure to perform at fixed time, in contract in which time is essential.—When a party to a contract promises to do a certain thing at or before a specified time, or certain things at or before specified times, and fails to do any such thing at or before the specified time, the contract, or so much of it as has not been performed, becomes voidable at the option of the promisee, if the intention of the parties was that time should be of the essence of the contract.",
    "56. Agreement to do impossible act.—An agreement to do an act impossible in itself is void.",
    "57. Reciprocal promise to do things legal, and also other things illegal.—Where persons reciprocally promise, firstly, to do certain things which are legal, and, secondly, under specified circumstances, to do certain other things which are illegal, the first set of promises is a contract, but the second is a void agreement.",
    "58. Alternative promise, one branch being illegal.—In the case of an alternative promise, one branch of which is legal and the other illegal, the legal branch alone can be enforced.",
    "59. Application of payment where debt to be discharged is indicated.—Where a debtor, owing several distinct debts to one person, makes a payment to him, either with express intimation, or under circumstances implying, that the payment is to be applied to the discharge of some particular debt, the payment, if accepted, must be applied accordingly.",
    "60. Application of payment where debt to be discharged is not indicated.—Where the debtor has omitted to intimate and there are no other circumstances indicating to which debt the payment is to be applied, the creditor may apply it at his discretion to any lawful debt actually due and payable to him from the debtor, whether its recovery is or is not barred by the law in force for the time being as to the limitation of suits.",
    "61. Application of payment where neither party appropriates.—Where neither party makes any appropriation, the payment shall be applied in discharge of the debts in order of time, whether they are or are not barred by the law in force for the time being as to the limitation of suits. If the debts are of equal standing, the payment shall be applied in discharge of each proportionably.",
    "62. Effect of novation, rescission, and alteration of contract.—If the parties to a contract agree to substitute a new contract for it, or to rescind or alter it, the original contract need not be performed.",
    "63. Promisee may dispense with or remit performance of promise.—Every promisee may dispense with or remit, wholly or in part, the performance of the promise made to him, or may extend the time for such performance, or may accept instead of it any satisfaction which he thinks fit.",
    "64. Consequences of rescission of voidable contract.—When a person at whose option a contract is voidable rescinds it, the other party thereto need not perform any promise therein contained in which he is promisor. The party rescinding a voidable contract shall, if he have received any benefit thereunder from another party to such contract, restore such benefit, so far as may be, to the person from whom it was received.",
    "65. Obligation of person who has received advantage under void agreement, or contract that becomes void.—When an agreement is discovered to be void, or when a contract becomes void, any person who has received any advantage under such agreement or contract is bound to restore it, or to make compensation for it to the person from whom he received it.",
    "66. Mode of communicating or revoking rescission of voidable contract.—The rescission of a voidable contract may be communicated or revoked in the same manner, and subject to the same rules, as apply to the communication or revocation of a proposal.",
    "67. Effect of neglect of promisee to afford promisor reasonable facilities for performance.—If any promisee neglects or refuses to afford the promisor reasonable facilities for the performance of his promise, the promisor is excused by such neglect or refusal as to any non-performance caused thereby.",
    "68. Claim for necessaries supplied to person incapable of contracting, or on his account.—If a person, incapable of entering into a contract, or any one whom he is legally bound to support, is supplied by another person with necessaries suited to his condition in life, the person who has furnished such supplies is entitled to be reimbursed from the property of such incapable person.",
    "69. Reimbursement of person paying money due by another, in payment of which he is interested.—A person who is interested in the payment of money which another is bound by law to pay, and who therefore pays it, is entitled to be reimbursed by the other.",
    "70. Obligation of person enjoying benefit of non-gratuitous act.—Where a person lawfully does anything for another person, or delivers anything to him, not intending to do so gratuitously, and such other person enjoys the benefit thereof, the latter is bound to make compensation to the former in respect of, or to restore, the thing so done or delivered.",
    "71. Responsibility of finder of goods.—A person who finds goods belonging to another, and takes them into his custody, is subject to the same responsibility as a bailee.",
    "72. Liability of person to whom money is paid, or thing delivered, by mistake or under coercion.—A person to whom money has been paid, or anything delivered, by mistake or under coercion, must repay or return it.",
    "73. Compensation for loss or damage caused by breach of contract.—When a contract has been broken, the party who suffers by such breach is entitled to receive, from the party who has broken the contract, compensation for any loss or damage caused to him thereby, which naturally arose in the usual course of things from such breach, or which the parties knew, when they made the contract, to be likely to result from the breach of it.",
    "74. Compensation for breach of contract where penalty stipulated for.—When a contract has been broken, if a sum is named in the contract as the amount to be paid in case of such breach, or if the contract contains any other stipulation by way of penalty, the party complaining of the breach is entitled, whether or not actual damage or loss is proved to have been caused thereby, to receive from the party who has broken the contract reasonable compensation not exceeding the amount so named or, as the case may be, the penalty stipulated for.",
    "75. Party rightfully rescinding contract, entitled to compensation.—A person who rightfully rescinds a contract is entitled to compensation for any damage which he has sustained through the non-fulfilment of the contract.",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "124. “Contract of indemnity” defined.—A contract by which one party promises to save the other from loss caused to him by the conduct of the promisor himself, or by the conduct of any other person, is called a “contract of indemnity”.",
    "125. Rights of indemnity-holder when sued.—The promisee in a contract of indemnity, acting within the scope of his authority, is entitled to recover from the promisor—\n(1) all damages which he may be compelled to pay in any suit in respect of any matter to which the promise to indemnify applies;\n(2) all costs which he may be compelled to pay in any such suit if, in bringing or defending it, he did not contravene the orders of the promisor, and acted as it would have been prudent for him to act in the absence of any contract of indemnity, or if the promisor authorized him to bring or defend the suit;\n(3) all sums which he may have paid under the terms of any compromise of any such suit, if the compromise was not contrary to the orders of the promisor, and was one which it would have been prudent for the promisee to make in the absence of any contract of indemnity, or if the promisor authorized him to compromise the suit.",
    "126. “Contract of guarantee”, “surety”, “principal debtor” and “creditor”.—A “contract of guarantee” is a contract to perform the promise, or discharge the liability, of a third person in case of his default. The person who gives the guarantee is called the “surety”; the person in respect of whose default the guarantee is given is called the “principal debtor”, and the person to whom the guarantee is given is called the “creditor”.",
    "127. Consideration for guarantee.—Anything done, or any promise made, for the benefit of the principal debtor, may be a sufficient consideration to the surety for giving the guarantee.",
    "128. Surety’s liability.—The liability of the surety is co-extensive with that of the principal debtor, unless it is otherwise provided by the contract.",
    "129. “Continuing guarantee”.—A guarantee which extends to a series of transactions, is called a “continuing guarantee”.",
    "130. Revocation of continuing guarantee.—A continuing guarantee may at any time be revoked by the surety, as to future transactions, by notice to the creditor.",
    "131. Revocation of continuing guarantee by surety’s death.—The death of the surety operates, in the absence of any contract to the contrary, as a revocation of a continuing guarantee, so far as regards future transactions.",
    "132. Liability of two persons, primarily liable, not affected by arrangement between them that one shall be surety on other’s default.—Where two persons contract with a third person to undertake a certain liability, and also contract with each other that one of them shall be liable only on the default of the other, the third person not being a party to such contract, the liability of each of such two persons to the third person under the first contract is not affected by the existence of the second contract, although such third person may have been aware of its existence.",
    "133. Discharge of surety by variance in terms of contract.—Any variance, made without the surety’s consent, in the terms of the contract between the principal debtor and the creditor, discharges the surety as to transactions subsequent to the variance.",
    "134. Discharge of surety by release or discharge of principal debtor.—The surety is discharged by any contract between the creditor and the principal debtor, by which the principal debtor is released, or by any act or omission of the creditor, the legal consequence of which is the discharge of the principal debtor.",
    "135. Discharge of surety when creditor compounds with, gives time to, or agrees not to sue, principal debtor.—A contract between the creditor and the principal debtor, by which the creditor makes a composition with, or promises to give time to, or not to sue, the principal debtor, discharges the surety, unless the surety assents to such contract.",
    "136. Surety not discharged when agreement made with third person to give time to principal debtor.—Where a contract to give time to the principal debtor is made by the creditor with a third person, and not with the principal debtor, the surety is not discharged.",
    "137. Creditor’s forbearance to sue does not discharge surety.—Mere forbearance on the part of the creditor to sue the principal debtor or to enforce any other remedy against him does not, in the absence of any provision in the guarantee to the contrary, discharge the surety.",
    "138. Release of one co-surety does not discharge others.—Where there are co-sureties, a release by the creditor of one of them does not discharge the others; neither does it free the surety so released from his responsibility to the other sureties.",
    "139. Discharge of surety by creditor’s act or omission impairing surety’s eventual remedy.—If the creditor does any act which is inconsistent with the rights of the surety, or omits to do any act which his duty to the surety requires him to do, and the eventual remedy of the surety himself against the principal debtor is thereby impaired, the surety is discharged.",
    "140. Rights of surety on payment or performance.—Where a guaranteed debt has become due, or default of the principal debtor to perform a guaranteed duty has taken place, the surety upon payment or performance of all that he is liable for, is invested with all the rights which the creditor had against the principal debtor.",
    "141. Surety’s right to benefit of creditor’s securities.—A surety is entitled to the benefit of every security which the creditor has against the principal debtor at the time when the contract of suretyship is entered into, whether the surety knows of the existence of such security or not; and if the creditor loses, or, without the consent of the surety, parts with such security, the surety is discharged to the extent of the value of the security.",
    "142. Guarantee obtained by misrepresentation invalid.—Any guarantee which has been obtained by means of misrepresentation made by the creditor, or with his knowledge and assent, concerning a material part of the transaction, is invalid.",
    "143. Guarantee obtained by concealment invalid.—Any guarantee which the creditor has obtained by means of keeping silence as to material circumstances, is invalid.",
    "144. Guarantee on contract that creditor shall not act on it until co-surety joins.—Where a person gives a guarantee upon a contract that the creditor shall not act upon it until another person has joined in it as co-surety, the guarantee is not valid if that other person does not join.",
    "145. Implied promise to indemnify surety.—In every contract of guarantee there is an implied promise by the principal debtor to indemnify the surety, and the surety is entitled to recover from the principal debtor whatever sum he has rightfully paid under the guarantee, but no sums which he has paid wrongfully.",
    "146. Co-sureties liable to contribute equally.—Where two or more persons are co-sureties for the same debt or duty, either jointly or severally, and whether under the same or different contracts, and whether with or without the knowledge of each other, the co-sureties, in the absence of any contract to the contrary, are liable, as between themselves, to pay each an equal share of the whole debt, or of that part of it which remains unpaid by the principal debtor.",
    "147. Liability of co-sureties bound in different sums.—Co-sureties who are bound in different sums are liable to pay equally as far as the limits of their respective obligations permit.",
    "148. “Bailment”, “bailor” and “bailee” defined.—A “bailment” is the delivery of goods by one person to another for some purpose, upon a contract that they shall, when the purpose is accomplished, be returned or otherwise disposed of according to the directions of the person delivering them. The person delivering the goods is called the “bailor”. The person to whom they are delivered is called the “bailee”.",
    "149. Delivery to bailee how made.—The delivery to the bailee may be made by doing anything which has the effect of putting the goods in the possession of the intended bailee or of any person authorized to hold them on his behalf.",
    "150. Bailor’s duty to disclose faults in goods bailed.—The bailor is bound to disclose to the bailee faults in the goods bailed, of which the bailor is aware, and which materially interfere with the use of them, or expose the bailee to extraordinary risks; and if he does not make such disclosure, he is responsible for damage arising to the bailee directly from such faults.",
    "151. Care to be taken by bailee.—In all cases of bailment the bailee is bound to take as much care of the goods bailed to him as a man of ordinary prudence would, under similar circumstances, take of his own goods of the same bulk, quality and value as the goods bailed.",
    "152. Bailee when not liable for loss, etc., of thing bailed.—The bailee, in the absence of any special contract, is not responsible for the loss, destruction or deterioration of the thing bailed, if he has taken the amount of care of it described in section 151.",
    "153. Termination of bailment by bailee’s act inconsistent with conditions.—A contract of bailment is avoidable at the option of the bailor, if the bailee does any act with regard to the goods bailed, inconsistent with the conditions of the bailment.",
    "154. Liability of bailee making unauthorized use of goods bailed.—If the bailee makes any use of the goods bailed which is not according to the conditions of the bailment, he is liable to make compensation to the bailor for any damage arising to the goods from or during such use of them.",
    "155. Effect of mixture, with bailor’s consent, of his goods with bailee’s.—If the bailee, with the consent of the bailor, mixes the goods of the bailor with his own goods, the bailor and the bailee shall have an interest, in proportion to their respective shares, in the mixture thus produced.",
    "156. Effect of mixture, without bailor’s consent, when the goods can be separated.—If the bailee, without the consent of the bailor, mixes the goods of the bailor with his own goods, and the goods can be separated or divided, the property in the goods remains in the parties respectively; but the bailee is bound to bear the expense of separation or division, and any damage arising from the mixture.",
    "157. Effect of mixture, without bailor’s consent, when the goods cannot be separated.—If the bailee, without the consent of the bailor, mixes the goods of the bailor with his own goods, in such a manner that it is impossible to separate the goods bailed from the other goods, and deliver them back, the bailor is entitled to be compensated by the bailee for the loss of the goods.",
    "158. Repayment, by bailor, of necessary expenses.—Where, by the conditions of the bailment, the goods are to be kept or to be carried, or to have work done upon them by the bailee for the bailor, and the bailee is to receive no remuneration, the bailor shall repay to the bailee the necessary expenses incurred by him for the purpose of the bailment.",
    "159. Restoration of goods lent gratuitously.—The lender of a thing for use may at any time require its return, if the loan was gratuitous, even though he lent it for a specified time or purpose. But if, on the faith of such loan made for a specified time or purpose, the borrower has acted in such a manner that the return of the thing lent before the time agreed upon would cause him loss exceeding the benefit actually derived by him from the loan, the lender must, if he compels the return, indemnify the borrower for the amount in which the loss so occasioned exceeds the benefit so derived.",
    "160. Return of goods bailed, on expiration of time or accomplishment of purpose.—It is the duty of the bailee to return, or deliver according to the bailor’s directions, the goods bailed, without demand, as soon as the time for which they were bailed has expired, or the purpose for which they were bailed has been accomplished.",
    "161. Bailee’s responsibility when goods are not duly returned.—If, by the default of the bailee, the goods are not returned, delivered or tendered at the proper time, he is responsible to the bailor for any loss, destruction or deterioration of the goods from that time.",
    "162. Termination of gratuitous bailment by death.—A gratuitous bailment is terminated by the death either of the bailor or of the bailee.",
    "163. Bailor entitled to increase or profit from goods bailed.—In the absence of any contract to the contrary, the bailee is bound to deliver to the bailor, or according to his directions, any increase or profit which may have accrued from the goods bailed.",
    "164. Bailor’s responsibility to bailee.—The bailor is responsible to the bailee for any loss which the bailee may sustain by reason that the bailor was not entitled to make the bailment, or to receive back the goods, or to give directions respecting them.",
    "165. Bailment by several joint owners.—If several joint owners of goods bail them, the bailee may deliver them back to, or according to the directions of, one joint owner without the consent of all in the absence of any agreement to the contrary.",
    "166. Bailee not responsible on re-delivery to bailor without title.—If the bailor has no title to the goods, and the bailee, in good faith, delivers them back to, or according to the directions of, the bailor, the bailee is not responsible to the owner in respect of such delivery.",
    "167. Right of third person claiming goods bailed.—If a person, other than the bailor, claims goods bailed, he may apply to the Court to stop the delivery of the goods to the bailor, and to decide the title to the goods.",
    "168. Right of finder of goods, may sue for specific reward offered.—The finder of goods has no right to sue the owner for compensation for trouble and expense voluntarily incurred by him to preserve the goods and to find out the owner; but he may retain the goods against the owner until he receives such compensation; and, where the owner has offered a specific reward for the return of goods lost, the finder may sue for such reward, and may retain the goods until he receives it.",
    "169. When finder of thing commonly on sale may sell it.—When a thing which is commonly the subject of sale is lost, if the owner cannot with reasonable diligence be found, or if he refuses, upon demand, to pay the lawful charges of the finder, the finder may sell it—\n(1) when the thing is in danger of perishing or of losing the greater part of its value, or,\n(2) when the lawful charges of the finder, in respect of the thing found, amount to two-thirds of its value.",
    "170. Bailee’s particular lien.—Where the bailee has, in accordance with the purpose of the bailment, rendered any service involving the exercise of labour or skill in respect of the goods bailed, he has, in the absence of a contract to the contrary, a right to retain such goods until he receives due remuneration for the services he has rendered in respect of them.",
    "171. General lien of bankers, factors, wharfingers, attorneys and policy-brokers.—Bankers, factors, wharfingers, attorneys of a High Court and policy-brokers may, in the absence of a contract to the contrary, retain as a security for a general balance of account, any goods bailed to them; but no other persons have a right to retain, as a security for such balance, goods bailed to them, unless there is an express contract to that effect.",
    "172. “Pledge”, “Pawnor” and “Pawnee” defined.—The bailment of goods as security for payment of a debt or performance of a promise is called “pledge”. The bailor is in this case called the “pawnor”. The bailee is called the “pawnee”.",
    "173. Pawnee’s right of retainer.—The pawnee may retain the goods pledged, not only for payment of the debt or the performance of the promise, but for the interest of the debt, and all necessary expenses incurred by him in respect of the possession or for the preservation of the goods pledged.",
    "174. Pawnee not to retain for debt or promise other than that for which goods pledged. Presumption in case of subsequent advances.—The pawnee shall not, in the absence of a contract to that effect, retain the goods pledged for any debt or promise other than the debt or promise for which they are pledged; but such contract, in the absence of anything to the contrary, shall be presumed in regard to subsequent advances made by the pawnee.",
    "175. Pawnee’s right as to extraordinary expenses incurred.—The pawnee is entitled to receive from the pawnor extraordinary expenses incurred by him for the preservation of the goods pledged.",
    "176. Pawnee’s right where pawnor makes default.—If the pawnor makes default in payment of the debt, or performance, at the stipulated time of the promise, in respect of which the goods were pledged, the pawnee may bring a suit against the pawnor upon the debt or promise, and retain the goods pledged as a collateral security; or he may sell the thing pledged, on giving the pawnor reasonable notice of the sale.",
    "177. Defaulting pawnor’s right to redeem.—If a time is stipulated for the payment of the debt, or performance of the promise, for which the pledge is made, and the pawnor makes default in payment of the debt or performance of the promise at the stipulated time, he may redeem the goods pledged at any subsequent time before the actual sale of them; but he must, in that case, pay, in addition, any expenses which have arisen from his default.",
    "178. Pledge by mercantile agent.—Where a mercantile agent is, with the consent of the owner, in possession of goods or the document of title to goods, any pledge made by him, when acting in the ordinary course of business of a mercantile agent, shall be as valid as if he were expressly authorized by the owner of the goods to make the same; provided that the pawnee acts in good faith and has not at the time of the pledge notice that the pawnor has not authority to pledge.",
    "178A. Pledge by person in possession under voidable contract.—When the pawnor has obtained possession of the goods pledged by him under a contract voidable under section 19 or section 19A, but the contract has not been rescinded at the time of the pledge, the pawnee acquires a good title to the goods, provided he acts in good faith and without notice of the pawnor’s defect of title.",
    "179. Pledge where pawnor has only a limited interest.—Where a person pledges goods in which he has only a limited interest, the pledge is valid to the extent of that interest.",
    "180. Suit by bailor or bailee against wrong-doer.—If a third person wrongfully deprives the bailee of the use or possession of the goods bailed, or does them any injury, the bailee is entitled to use such remedies as the owner might have used in the like case if no bailment had been made; and either the bailor or the bailee may bring a suit against a third person for such deprivation or injury.",
    "181. Apportionment of relief or compensation obtained by such suits.—Whatever is obtained by way of relief or compensation in any such suit shall, as between the bailor and the bailee, be dealt with according to their respective interests.",
    "182. “Agent” and “principal” defined.—An “agent” is a person employed to do any act for another, or to represent another in dealings with third persons. The person for whom such act is done, or who is so represented, is called the “principal”.",
    "183. Who may employ agent.—Any person who is of the age of majority according to the law to which he is subject, and who is of sound mind, may employ an agent.",
    "184. Who may be an agent.—As between the principal and third persons, any person may become an agent, but no person who is not of the age of majority and of sound mind can become an agent, so as to be responsible to his principal according to the provisions in that behalf herein contained.",
    "185. Consideration not necessary.—No consideration is necessary to create an agency.",
    "186. Agent’s authority may be expressed or implied.—The authority of an agent may be expressed or implied.",
    "187. Definitions of express and implied authority.—An authority is said to be express when it is given by words spoken or written. An authority is said to be implied when it is to be inferred from the circumstances of the case; and things spoken or written, or the ordinary course of dealing, may be accounted circumstances of the case.",
    "188. Extent of agent’s authority.—An agent, having an authority to do an act, has authority to do every lawful thing which is necessary in order to do such act.",
    "189. Agent’s authority in an emergency.—An agent has authority, in an emergency, to do all such acts for the purpose of protecting his principal from loss as would be done by a person of ordinary prudence, in his own case, under similar circumstances.",
    "190. When agent cannot delegate.—An agent cannot lawfully employ another to perform acts which he has expressly or impliedly undertaken to perform personally, unless by the ordinary custom of trade a sub-agent may, or, from the nature of the agency, a sub-agent must, be employed.",
    "191. “Sub-agent” defined.—A “sub-agent” is a person employed by, and acting under the control of, the original agent in the business of the agency.",
    "192. Representation of principal by sub-agent properly appointed.—Where a sub-agent is properly appointed, the principal is, so far as regards third persons, represented by the sub-agent, and is bound by and responsible for his acts, as if he were an agent originally appointed by the principal.",
    "193. Agent’s responsibility for sub-agent appointed without authority.—Where an agent, without having authority to do so, has appointed a person to act as a sub-agent, the agent stands towards such person in the relation of a principal to an agent, and is responsible for his acts both to the principal and to third persons; the principal is not represented by or responsible for the acts of the person so employed, nor is that person responsible to the principal.",
    "194. Relation between principal and person duly appointed by agent to act in business of agency.—Where an agent, holding an express or implied authority to name another person to act for the principal in the business of the agency, has named another person accordingly, such person is not a sub-agent, but an agent of the principal for such part of the business of the agency as is entrusted to him.",
    "195. Agent’s duty in naming such person.—In selecting such agent for his principal, an agent is bound to exercise the same amount of discretion as a man of ordinary prudence would exercise in his own case; and, if he does this, he is not responsible to the principal for the acts or negligence of the agent so selected.",
    "196. Right of person as to acts done for him without his authority. Effect of ratification.—Where acts are done by one person on behalf of another, but without his knowledge or authority, he may elect to ratify or to disown such acts. If he ratify them, the same effects will follow as if they had been performed by his authority.",
    "197. Ratification may be expressed or implied.—Ratification may be expressed or may be implied in the conduct of the person on whose behalf the acts are done.",
    "198. Knowledge requisite for valid ratification.—No valid ratification can be made by a person whose knowledge of the facts of the case is materially defective.",
    "199. Effect of ratifying unauthorized act forming part of a transaction.—A person ratifying any unauthorized act done on his behalf ratifies the whole of the transaction of which such act formed a part.",
    "200. Ratification of unauthorized act cannot injure third person.—An act done by one person on behalf of another, without such other person’s authority, which, if done with authority, would have the effect of subjecting a third person to damages, or of terminating any right or interest of a third person, cannot, by ratification, be made to have such effect.",
    "201. Termination of agency.—An agency is terminated by the principal revoking his authority; or by the agent renouncing the business of the agency; or by the business of the agency being completed; or by either the principal or agent dying or becoming of unsound mind; or by the principal being adjudicated an insolvent under the provisions of any Act for the time being in force for the relief of insolvent debtors.",
    "202. Termination of agency, where agent has an interest in subject-matter.—Where the agent has himself an interest in the property which forms the subject-matter of the agency, the agency cannot, in the absence of an express contract, be terminated to the prejudice of such interest.",
    "203. When principal may revoke agent’s authority.—The principal may, save as is otherwise provided by the last preceding section, revoke the authority given to his agent at any time before the authority has been exercised so as to bind the principal.",
    "204. Revocation where authority has been partly exercised.—The principal cannot revoke the authority given to his agent after the authority has been partly exercised, so far as regards such acts and obligations as arise from acts already done in the agency.",
    "205. Compensation for revocation by principal, or renunciation by agent.—Where there is an express or implied contract that the agency should be continued for any period of time, the principal must make compensation to the agent, or the agent to the principal, as the case may be, for any previous revocation or renunciation of the agency without sufficient cause.",
    "206. Notice of revocation or renunciation.—Reasonable notice must be given of such revocation or renunciation, otherwise the damage thereby resulting to the principal or the agent, as the case may be, must be made good to the one by the other.",
    "207. Revocation and renunciation may be expressed or implied.—Revocation and renunciation may be expressed or may be implied in the conduct of the principal or agent respectively.",
    "208. When termination of agent’s authority takes effect as to agent, and as to third persons.—The termination of the authority of an agent does not, so far as regards the agent, take effect before it becomes known to him, or, so far as regards third persons, before it becomes known to them.",
    "209. Agent’s duty on termination of agency by principal’s death or insanity.—When an agency is terminated by the principal dying or becoming of unsound mind, the agent is bound to take, on behalf of the representatives of his late principal, all reasonable steps for the protection and preservation of the interests entrusted to him.",
    "210. Termination of sub-agent’s authority.—The termination of the authority of an agent causes the termination (subject to the rules herein contained regarding the termination of an agent’s authority) of the authority of all sub-agents appointed by him.",
    "211. Agent’s duty in conducting principal’s business.—An agent is bound to conduct the business of his principal according to the directions given by the principal, or, in the absence of any such directions, according to the custom which prevails in doing business of the same kind at the place where the agent conducts such business. When the agent acts otherwise, if any loss be sustained, he must make it good to his principal, and if any profit accrues, he must account for it.",
    "212. Skill and diligence required from agent.—An agent is bound to conduct the business of the agency with as much skill as is generally possessed by persons engaged in similar business, unless the principal has notice of his want of skill. The agent is always bound to act with reasonable diligence, and to use such skill as he possesses; and to make compensation to his principal in respect of the direct consequences of his own neglect, want of skill, or misconduct, but not in respect of loss or damage which are indirectly or remotely caused by such neglect, want of skill, or misconduct.",
    "213. Agent’s accounts.—An agent is bound to render proper accounts to his principal on demand.",
    "214. Agent’s duty to communicate with principal.—It is the duty of an agent, in cases of difficulty, to use all reasonable diligence in communicating with his principal, and in seeking to obtain his instructions.",
    "215. Right of principal when agent deals, on his own account, in business of agency without principal’s consent.—If an agent deals on his own account in the business of the agency, without first obtaining the consent of his principal and acquainting him with all material circumstances which have come to his own knowledge on the subject, the principal may repudiate the transaction, if the case shows, either that any material fact has been dishonestly concealed from him by the agent, or that the dealings of the agent have been disadvantageous to him.",
    "216. Principal’s right to benefit gained by agent dealing on his own account in business of agency.—If an agent, without the knowledge of his principal, deals in the business of the agency on his own account instead of on account of his principal, the principal is entitled to claim from the agent any benefit which may have resulted to him from the transaction.",
    "217. Agent’s right of retainer out of sums received on principal’s account.—An agent may retain, out of any sums received on account of the principal in the business of the agency, all moneys due to himself in respect of advances made or expenses properly incurred by him in conducting such business, and also such remuneration as may be payable to him for acting as agent.",
    "218. Agent’s duty to pay sums received for principal.—Subject to such deductions, the agent is bound to pay to his principal all sums received on his account.",
    "219. When agent’s remuneration becomes due.—In the absence of any special contract, payment for the performance of any act is not due to the agent until the completion of such act; but an agent may detain moneys received by him on account of goods sold, although the whole of the goods consigned to him for sale may not have been sold, or although the sale may not be actually complete.",
    "220. Agent not entitled to remuneration for business misconducted.—An agent who is guilty of misconduct in the business of the agency is not entitled to any remuneration in respect of that part of the business which he has misconducted.",
    "221. Agent’s lien on principal’s property.—In the absence of any contract to the contrary, an agent is entitled to retain goods, papers and other property, whether movable or immovable of the principal received by him, until the amount due to himself for commission, disbursements and services in respect of the same has been paid or accounted for to him.",
    "222. Agent to be indemnified against consequences of lawful acts.—The employer of an agent is bound to indemnify him against the consequences of all lawful acts done by such agent in exercise of the authority conferred upon him.",
    "223. Agent to be indemnified against consequences of acts done in good faith.—Where one person employs another to do an act, and the agent does the act in good faith, the employer is liable to indemnify the agent against the consequences of that act, though it cause an injury to the rights of third persons.",
    "224. Non-liability of employer of agent to do a criminal act.—Where one person employs another to do an act which is criminal, the employer is not liable to the agent, either upon an express or an implied promise, to indemnify him against the consequences of that Act.",
    "225. Compensation to agent for injury caused by principal’s neglect.—The principal must make compensation to his agent in respect of injury caused to such agent by the principal’s neglect or want of skill.",
    "226. Enforcement and consequences of agent’s contracts.—Contracts entered into through an agent, and obligations arising from acts done by an agent, may be enforced in the same manner, and will have the same legal consequences, as if the contracts had been entered into and the acts done by the principal in person.",
    "227. Principal how far bound, when agent exceeds authority.—When an agent does more than he is authorized to do, and when the part of what he does, which is within his authority, can be separated from the part which is beyond his authority, so much only of what he does as is within his authority is binding as between him and his principal.",
    "228. Principal not bound when excess of agent’s authority is not separable.—Where an agent does more than he is authorized to do, and what he does beyond the scope of his authority cannot be separated from what is within it, the principal is not bound to recognize the transaction.",
    "229. Consequences of notice given to agent.—Any notice given to or information obtained by the agent, provided it be given or obtained in the course of the business transacted by him for the principal, shall, as between the principal and third parties, have the same legal consequences as if it had been given to or obtained by the principal.",
    "230. Agent cannot personally enforce, nor be bound by, contracts on behalf of principal.—In the absence of any contract to that effect, an agent cannot personally enforce contracts entered into by him on behalf of his principal, nor is he personally bound by them.",
    "231. Rights of parties to a contract made by agent not disclosed.—If an agent makes a contract with a person who neither knows, nor has reason to suspect, that he is an agent, his principal may require the performance of the contract; but the other contracting party has, as against the principal, the same rights as he would have had as against the agent if the agent had been principal.",
    "232. Performance of contract with agent supposed to be principal.—Where one man makes a contract with another, neither knowing nor having reasonable ground to suspect that the other is an agent, the principal, if he requires the performance of the contract, can only obtain such performance subject to the rights and obligations subsisting between the agent and the other party to the contract.",
    "233. Right of person dealing with agent personally liable.—In cases where the agent is personally liable, a person dealing with him may hold either him or his principal, or both of them, liable.",
    "234. Consequence of inducing agent or principal to act on belief that principal or agent will be held exclusively liable.—When a person who has made a contract with an agent induces the agent to act upon the belief that the principal only will be held liable, or induces the principal to act upon the belief that the agent only will be held liable, he cannot afterwards hold liable the agent or principal respectively.",
    "235. Liability of pretended agent.—A person untruly representing himself to be the authorized agent of another, and thereby inducing a third person to deal with him as such agent, is liable, if his alleged employer does not ratify his acts, to make compensation to the other in respect of any loss or damage which he has incurred by so dealing.",
    "236. Person falsely contracting as agent not entitled to performance.—A person with whom a contract has been entered into in the character of agent, is not entitled to require the performance of it, if he was in reality acting, not as agent, but on his own account.",
    "237. Liability of principal inducing belief that agent’s unauthorized acts were authorized.—When an agent has, without authority, done acts or incurred obligations to third persons on behalf of his principal, the principal is bound by such acts or obligations, if he has by his words or conduct induced such third persons to believe that such acts and obligations were within the scope of the agent’s authority.",
    "238. Effect, on agreement, of misrepresentation or fraud by agent.—Misrepresentation made, or frauds committed, by agents acting in the course of their business for their principals, have the same effect on agreements made by such agents as if such misrepresentations or frauds had been made or committed by the principals; but misrepresentations made, or frauds committed, by agents, in matters which do not fall within their authority, do not affect their principals.",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
    "[Repealed.].",
]
chapter_list = [
    [],
    [3, 4, 5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22],
    [31, 32, 33, 34, 35, 36],
    [
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
    ],
    [68, 69, 70, 71, 72],
    [73, 74, 75],
    [
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
    ],
    [
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
    ],
    [
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        178,
        179,
        180,
        181,
    ],
    [
        182,
        183,
        184,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
        200,
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        215,
        216,
        217,
        218,
        219,
        220,
        221,
        222,
        223,
        224,
        225,
        226,
        227,
        228,
        229,
        230,
        231,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
    ],
    [
        239,
        240,
        241,
        242,
        243,
        244,
        245,
        246,
        247,
        248,
        249,
        250,
        251,
        252,
        253,
        254,
        255,
        256,
        257,
        258,
        259,
        260,
        261,
        262,
        263,
        264,
        265,
        266,
    ],
]


def _validate_section_index(idx: int) -> None:
    """Raise a clear error if section index is invalid."""
    if not isinstance(idx, int):
        raise TypeError(f"Section index must be int, got {type(idx).__name__}")
    if idx < 1 or idx >= len(section_list):
        raise ValueError(
            f"Section index {idx} out of range. "
            f"Valid range is 1 to {len(section_list) - 1}."
        )


def _validate_chapter_index(idx: int) -> None:
    """Raise a clear error if chapter index is invalid."""
    if not isinstance(idx, int):
        raise TypeError(f"Chapter index must be int, got {type(idx).__name__}")
    if idx < 1 or idx >= len(chapter_list):
        raise ValueError(
            f"Chapter index {idx} out of range. "
            f"Valid range is 1 to {len(chapter_list) - 1}."
        )


def get_section(from_index: int, to_index: int) -> Dict[str, Any]:
    """
    Return a structured view of sections in [from_index, to_index].
    0<from_index<to_index<=number of sections in indian contracts act (now: 238)

    Output format:

    {
        "from": int,
        "to": int,
        "sections": [
            {"section": int, "text": str}
        ]
    }
    """
    if not isinstance(from_index, int) or not isinstance(to_index, int):
        raise TypeError("from_index and to_index must be integers")

    # allow reversed ranges
    start = min(from_index, to_index)
    end = max(from_index, to_index)

    _validate_section_index(start)
    _validate_section_index(end)

    sections = []
    for idx in range(start, end + 1):
        text = section_list[idx] if idx < len(section_list) else ""
        sections.append(
            {
                "section": idx,
                "text": text or "",
            }
        )

    return {
        "from": start,
        "to": end,
        "sections": sections,
    }


def get_chapter_section_list(chapter_idx: int) -> Dict[str, Any]:
    """
    Return all sections for a chapter in a structured way.
    0<chapter_idx<=number of chapters in indian contracts act (now: 11)
    Output format:

    {
        "chapter": int,
        "sections": [
            {"section": int, "text": str}
        ]
    }
    """
    _validate_chapter_index(chapter_idx)

    section_numbers = chapter_list[chapter_idx]
    if not isinstance(section_numbers, list):
        raise TypeError(
            f"chapter_list[{chapter_idx}] must be a list of section numbers"
        )

    sections = []
    for sec in section_numbers:
        _validate_section_index(sec)
        text = section_list[sec] if sec < len(section_list) else ""
        sections.append(
            {
                "section": sec,
                "text": text or "",
            }
        )

    return {
        "chapter": chapter_idx,
        "sections": sections,
    }
